apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crud-auth-external-secrets
  namespace: crud-app
spec:
  refreshInterval: 30m          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store-dev     # name of the SecretStore (or kind specified)
  target:
    name: crud-auth-secrets  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "SECRET_KEY"
      remoteRef:
        key: crud-auth-1
        version: latest
        property: SECRET_KEY # JSON property
    - secretKey: "GH_CLIENT_ID"
      remoteRef:
        key: crud-auth-1
        version: latest
        property: GH_CLIENT_ID # JSON property
    - secretKey: "GH_CLIENT_SECRET"
      remoteRef:
        key: crud-auth-1
        version: latest
        property: GH_CLIENT_SECRET # JSON property
