apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
helmCharts:
  - name: external-secrets
    namespace: external-secrets
    releaseName: external-secrets
    version: 0.10.0
    repo: https://charts.external-secrets.io
    includeCRDs: true
resources:
  - ./namespace.yaml
  - ./crds/kubernetes-client.io_externalsecrets_crd.yaml
  - ./secret-store.yaml
