repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-format
        name: "Ruff: Format code"
      - id: ruff
        name: "Ruff: Lint code"
        args: ["--fix"]
  - repo: local
    hooks:
      - id: ty
        name: "Ty: Type checking"
        entry: .venv/bin/ty check
        language: system
        types: [python]