version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crud-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  crud-auth-github:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: crud-auth-github
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8000:8000
    depends_on:
      - db
