version: "3"

services:
  crud-auth-github-service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: crud-auth-github
    volumes:
      - .:/app
    ports:
      - 8000:8000

  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"