version: '3'
services:
  crud-auth-github:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: crud-auth-github
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
#      - POSTGRES_NAME=crud_auth_db
#      - POSTGRES_USER=crud_auth_user
#      - POSTGRES_PASSWORD=password
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 15432:5432

volumes:
  postgres_data: