kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: crud-app
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-pv