apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-auth-github
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-auth-github
  template:
    metadata:
      labels:
        app: crud-auth-github
    spec:
      containers:
      - name: crud-auth-github
        image: piwero/crud_auth_github-crud-auth-github:latest
        imagePullPolicy: IfNotPresent
        ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
            - name: grpc
              containerPort: 9999
              protocol: TCP
        env:
        - name: GH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: GH_CLIENT_ID
        - name: GH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: GH_CLIENT_SECRET
      volumes:
      - name: app-volume
        emptyDir: {}

