# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: Gr1N/setup-poetry@v9
    - run: poetry --version
    
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry env use 3.11
        poetry env info
        poetry install

    - name: Run linters
      run: |
        source .venv/bin/activate
        ruff .
        black .

    - name: Test with pytest
      env:
        SECRET_KEY:  ${{ secrets.SECRET_KEY }}
        DEBUG:  ${{ secrets.DEBUG }}
        GH_CLIENT_ID: "###"
        GH_CLIENT_SECRET: "###"
      run: |
        source .venv/bin/activate
        python manage.py collectstatic
        pytest --cov=. -n auto # Run tests with coverage and in parallel
